@startuml
'https://plantuml.com/object-diagram

object "<u> c1: Course" as c1 {
    name: "CS5800 - Advanced Software Engineering"

}

object "<u>c1Instructor: Instructor" as c1Instructor {
    firstName : "Nima"
    lastName : "Davarpanah"
    String officeNumber : "3-2636"
}

object "<u>c1Textbook:Textbook" as c1Textbook {
    title : "Robert Cecil Martin"
    author: "Pearson"
    publisher : "CleanCode:A Handbook of Agile Software Craftsmanship"
}

c1  o--  c1Instructor
c1  o--  c1Textbook

@enduml
